### PR TITLE
Home.js with offset utc date

### PR DESCRIPTION
**Pull request by avenida714**
updated Home.js to better deal with time-zone conversion

### CODE REVIEW

**Comment by francisli** [comment]
@avenida714 in Slack you were asking how to test this... from just inspecting the data in your database and comparing against what you see in the graph, do you see correct output?

**Comment by avenida714** [comment]
There is a difference in time by 8 hours.

before change
after change

**Comment by avenida714** [comment]
I don't think my changes are correct; the goal was to have the dates "corrected" to be later, not earlier, unless I've misunderstood the bug.

**Comment by francisli** [comment]
Closing this in favor of the server-side fix in #166

**Pull request closed without merging**
